# Generated by Django 2.2.6 on 2020-06-25 01:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('project_leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostIt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=90)),
                ('description', models.TextField(blank=True)),
                ('stakeholders_vote', models.IntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'No contestado')], default=2)),
                ('developers_vote', models.IntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'No contestado')], default=2)),
                ('status', models.CharField(choices=[('O', 'Open'), ('A', 'Approvecd'), ('R', 'Rejected'), ('F', 'Filed')], default='O', max_length=1)),
                ('section', models.IntegerField(choices=[(0, 'Objetivos'), (1, 'Usuarios'), (2, 'Fuentes'), (3, 'Conceptos'), (4, 'Métricas e Indicadores'), (5, 'Generación de Conceptos'), (6, 'Generación de Métricas'), (7, 'Visualización, Notificación y Acción'), (8, 'Entorno')])),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
            ],
        ),
        migrations.CreateModel(
            name='WorkIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_leader', models.BooleanField(default=False)),
                ('team', models.CharField(choices=[('D', 'Developer'), ('S', 'Stakeholder'), ('U', 'Unassigned')], default='U', max_length=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'No contestado')], default=2)),
                ('team', models.CharField(choices=[('D', 'Developer'), ('S', 'Stakeholder')], max_length=1)),
                ('postit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostIt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'postit')},
            },
        ),
    ]
