# Generated by Django 2.2.6 on 2019-10-14 18:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.RenameField(
            model_name='postit',
            old_name='descripcion',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='postit',
            old_name='titulo',
            new_name='title',
        ),
        migrations.AddField(
            model_name='postit',
            name='section',
            field=models.IntegerField(choices=[(0, 'Objetivos'), (1, 'Usuarios'), (2, 'Fuentes'), (3, 'Conceptos'), (4, 'Métricas e Indicadores'), (5, 'Generación de Conceptos'), (6, 'Generación de Métricas'), (7, 'Visualización, Notificación y Acción'), (8, 'Entorno')], default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postit',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('A', 'Approvecd'), ('R', 'Rejected'), ('F', 'Filed')], default='o', max_length=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='WorkIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_lider', models.BooleanField(default=False)),
                ('team', models.CharField(choices=[('D', 'Developer'), ('S', 'Stakeholder')], max_length=1)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Board')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VoteIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.IntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'No contestado')], default=2)),
                ('team', models.CharField(choices=[('D', 'Developer'), ('S', 'Stakeholder')], max_length=1)),
                ('postit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.PostIt')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='postit',
            name='board',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.Board'),
            preserve_default=False,
        ),
    ]
