# Generated by Django 2.2.6 on 2019-11-08 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20191014_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postit',
            name='status',
            field=models.CharField(choices=[('O', 'Open'), ('A', 'Approvecd'), ('R', 'Rejected'), ('F', 'Filed')], default='O', max_length=1),
        ),
        migrations.AlterField(
            model_name='workin',
            name='team',
            field=models.CharField(choices=[('D', 'Developer'), ('S', 'Stakeholder'), ('U', 'Unassigned')], default='U', max_length=1),
        ),
    ]
