# Generated by Django 2.2.6 on 2019-11-17 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20191108_1943'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workin',
            old_name='is_lider',
            new_name='is_leader',
        ),
    ]
