# Generated by Django 2.2.6 on 2019-12-04 13:06

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0004_auto_20191117_1853'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='votein',
            unique_together={('user', 'postit')},
        ),
    ]
