# Generated by Django 2.2.6 on 2019-12-22 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_board_proyect_leader'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='proyect_leader',
            new_name='project_leader',
        ),
        migrations.AddField(
            model_name='postit',
            name='developers_vote',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'No contestado')], default=2),
        ),
        migrations.AddField(
            model_name='postit',
            name='stakeholders_vote',
            field=models.IntegerField(choices=[(0, 'No'), (1, 'Si'), (2, 'No contestado')], default=2),
        ),
    ]
